name:                hgrep
version:             0.1.0.0
github:              "github.com/blueburningcoder/hgrep"
license:             BSD3
author:              "Felix Karg"
maintainer:          "felix.karg@uranus.uni-freiburg.de"
copyright:           "2018 Felix Karg"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/hgrep#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hgrep-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hgrep
    - optparse-applicative

tests:
  hgrep-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hgrep
